Reg 47/course blocks
olin/register pull request #28
Opened 2017-04-30 20:20 UTC by arianaolson419

https://olinjs.atlassian.net/browse/REG-47

Planned Courses can be dragged and placed into different semesters. The semester of the course is updated in the state when the course is moved to a new semester.

![image](https://cloud.githubusercontent.com/assets/15851197/25567656/c608902e-2dc0-11e7-9517-adda6bc7db07.png)

![image](https://cloud.githubusercontent.com/assets/15851197/25567661/dcd18270-2dc0-11e7-99c6-1a4e01759555.png)

2017-04-30 20:21 UTC, arianaolson419 commented
The second screenshot is of me dragging the course.

2017-04-30 23:49 UTC, arianaolson419 commented on src/reducers/LoginReducer.jsx
> +    }
So... the state that I need is in LoginReducer, which doesn't really make sense for actions that have nothing to do with logging in... Would it be better to split up receiving the state at login into a different reducer, or to just change the name of the file to encompass all the actions it handles?

2017-04-30 23:49 UTC, robertsiegel commented
Only wondering if we should change around the state so that it can be in a different reducer or rename LoginReducer so that it makes more sense to have CHANGE_SEMESTER in there. Other than that it looks good!

2017-04-30 23:57 UTC, robbie-sundstrom approved these changes
Other than Ariana's comment about the LoginReducer, I think everything looks good!

2017-05-01 21:52 UTC, billmwong requested changes
Damn Ariana, this code is awesome.  Two comments.

2017-05-01 21:52 UTC, billmwong commented on src/reducers/LoginReducer.jsx
> +    }
I'm confused, isn't the Redux state global?  So you should be able to access `state.plannedCourses` from any reducer, and then separating out this `CHANGE_SEMESTER` reducer case should be easy.

2017-05-01 21:52 UTC, billmwong commented on src/containers/SemesterReserveContainer.jsx
> +    // return drop result available to the drag sourc
I think you're missing an 'e' in 'source'

2017-05-01 23:06 UTC, arianaolson419 commented on src/containers/SemesterReserveContainer.jsx
> +    // return drop result available to the drag sourc
Not the way the state is structured now as far as I can tell... We were combining reducers in the wrong way. I'm working on improving that on another card. I'll fix the 'e'!

2017-05-01 23:12 UTC, billmwong approved these changes
Cool, if that combining reducers bug turns out to be too much, write it on a future ticket for reference and skip it!

2017-05-01 23:15 UTC, merged