Adds student, course, and student-course schemae
olin/register pull request #9
Opened 2017-03-28 21:00 UTC by logandavis

This is the first pass for the student, course, and student-course
instance schemae. They may need to be updated later in order to
make requirements really work, or to add sanitation beyond just typing.

2017-03-28 21:02 UTC, logandavis commented
JIRA: https://olinjs.atlassian.net/browse/REG-6
https://olinjs.atlassian.net/browse/REG-7

2017-03-28 22:50 UTC, Halliax reviewed
Logan the fact that studentCourseSchema doesn't follow the naming convention bothers me. Otherwise this seems fine (as students, should we explicitly approve these? Or is a comment review like this fine)

2017-03-29 00:16 UTC, billmwong requested changes
In addition to the in-line comments, update the syntax to be es6 please!  Look at my wiki entry [here](https://github.com/olin/register/wiki/ES6-Basics) for the basics on what you need to know for es6.

Also remember to name your PRs with your Jira ticket number in it.

2017-03-29 00:16 UTC, billmwong commented on models/studentCourseSchema.js
> +module.exports = mongoose.model("StudentCourse", studentCourseSchema);
newline at end of file

2017-03-29 00:16 UTC, billmwong commented on models/courseModel.js
> +// Create course Schema
I'd remove these comments, it doesn't tell the reader any more info than the code does

2017-03-29 00:16 UTC, billmwong commented on models/courseModel.js
> +  NDGRCredits: Number,
Remind me what `NDGR` stands for?

2017-03-29 00:16 UTC, billmwong commented on models/studentCourseSchema.js
> +var Schema = mongoose.Schema;
Don't need to set this variable if you specify `mongoose.Schema` below

2017-03-29 05:27 UTC, logandavis commented on models/courseModel.js
> +  NDGRCredits: Number,
Non-degree.

2017-03-29 05:36 UTC, logandavis commented
@Halliax which naming conventions does studentCourseSchema break? I'm looking at this: https://google.github.io/styleguide/jsoncstyleguide.xml

2017-03-29 05:40 UTC, logandavis commented on models/studentCourseSchema.js
> +module.exports = mongoose.model("StudentCourse", studentCourseSchema);
Github didn't catch that my new commit obsoleted this comment, but it did. Done.

2017-03-29 18:03 UTC, billmwong requested changes
Sorry to be nitpicky, but rebase from master and run `npm start` to see the backend linter on your files here, and fix the errors.  Mostly using single-quote strings and comma dangles.  Also rebasing will fix the merge conflicts.

2017-03-30 20:42 UTC, Halliax commented
@logandavis I just meant the file name, with your other filenames. The other schema files are "model"

2017-03-31 04:15 UTC, billmwong approved these changes

2017-03-31 04:16 UTC, merged